/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontent;

import Backend.ControladorDeArchivo;
import Backend.RespuestaArchivo;
import Excepciones.ErrorDeArchivoException;
import java.awt.Font;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class PromtZal extends javax.swing.JFrame {
    
    private final ControladorDeArchivo controlador;
    private final JFileChooser fileChooser;
    
    public PromtZal(ControladorDeArchivo controlador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlador = controlador;
        fileChooser = new JFileChooser();
        jTextArea1.setFont(new Font("Liberarion Sans", 0, 22));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnCargar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCrearPromt = new javax.swing.JButton();
        btnGuardarArchivo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargar.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        btnCargar.setText("Cargar Archivo");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        btnGuardarCambios.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(this::btnGuardarCambiosActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnCrearPromt.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        btnCrearPromt.setText("Limpiar y Crear Promt");
        btnCrearPromt.addActionListener(this::btnCrearPromtActionPerformed);

        btnGuardarArchivo.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        btnGuardarArchivo.setText("Guardar Archivo");
        btnGuardarArchivo.addActionListener(this::btnGuardarArchivoActionPerformed);

        jDesktopPane1.setLayer(btnCargar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnGuardarCambios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCrearPromt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnGuardarArchivo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btnCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearPromt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarArchivo)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar)
                    .addComponent(btnGuardarCambios)
                    .addComponent(btnCrearPromt)
                    .addComponent(btnGuardarArchivo))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        fileChooser.setSelectedFile(null);
        int resultado = fileChooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File  archivo = fileChooser.getSelectedFile();
            try {
                RespuestaArchivo respuesta = controlador.cargarArchivo(archivo);
                if (respuesta.isValido()) {
                    jTextArea1.setText(respuesta.getMensaje());
                    mostrarBtnGuardar(false);
                } else {
                    mostrarMensaje(respuesta.getMensaje());
                }
            } catch (ErrorDeArchivoException e) {
                mostrarMensaje(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        try {
            controlador.guardarCambios(jTextArea1.getText());
        } catch (ErrorDeArchivoException e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnCrearPromtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPromtActionPerformed
        controlador.setArchivoAbierto(null);
        jTextArea1.setText("");
        mostrarBtnGuardar(true);
    }//GEN-LAST:event_btnCrearPromtActionPerformed

    private void btnGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivoActionPerformed
        fileChooser.setSelectedFile(null);
        int resultado = fileChooser.showSaveDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                controlador.crearArchivo(archivo, jTextArea1.getText());
                mostrarBtnGuardar(false);
            } catch (ErrorDeArchivoException e) {
                mostrarMensaje(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnGuardarArchivoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrearPromt;
    private javax.swing.JButton btnGuardarArchivo;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    
    private void mostrarBtnGuardar(boolean mostrar) {
        btnGuardarArchivo.setVisible(mostrar);
    }
    
}
